name: tarot_diary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  # 캘린더
  table_calendar: ^3.1.2

  # 아이콘
  cupertino_icons: ^1.0.8

  # 인증 (Firebase는 Auth만 유지)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1

  # UI
  google_fonts: ^8.0.0

  # 로컬 DB (SQLite)
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.9.0

  # 네트워크/구글 API (필요 시 유지)
  http: ^1.2.0
  googleapis: ^13.2.0

  # 유틸
  archive: ^3.5.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  uuid: ^4.4.0

  # 광고
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # home
    - asset/main_top.webp
    - asset/main_bottom.webp

    #icon
    - asset/icon_write_diary.png
    - asset/icon_list_diary.png
    - asset/icon_arcana.png

    # cards
    - asset/cards/
